import React, { useState } from 'react';
import { TrendAnalysisResult, SearchParams } from '../types';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';

interface DashboardHeaderProps {
  data: TrendAnalysisResult;
  searchParams: SearchParams | null;
}

const DashboardHeader: React.FC<DashboardHeaderProps> = ({ data, searchParams }) => {
  const [copied, setCopied] = useState(false);

  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-600';
    if (score >= 50) return 'text-blue-600';
    return 'text-red-500';
  };

  const getCompLabel = (level: string) => {
    switch (level.toLowerCase()) {
      case 'low': return '낮음';
      case 'medium': return '보통';
      case 'high': return '높음';
      case 'very high': return '매우 높음';
      default: return level;
    }
  };

  const getCompColor = (level: string) => {
    switch (level.toLowerCase()) {
      case 'low': return 'text-green-600 bg-green-100';
      case 'medium': return 'text-amber-600 bg-amber-100';
      case 'high': return 'text-red-600 bg-red-100';
      case 'very high': return 'text-red-800 bg-red-200';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const barColors = ['#8884d8', '#82ca9d', '#ffc658', '#ff8042', '#8dd1e1'];

  const handleCopyReport = () => {
    const report = `
📊 [유튜브 트렌드 분석 리포트]
🔍 키워드: ${searchParams?.keyword || '알 수 없음'} (${searchParams?.language || '-'})

🚀 성장 잠재력: ${data.growthScore}/100
🛡️ 경쟁 강도: ${getCompLabel(data.competitionLevel)}

💡 AI 3줄 요약:
${data.summary}

🔥 급상승 핵심 토픽:
${data.trendTopics.map(t => `- ${t.topic} (관심도: ${t.score})`).join('\n')}

Generated by YouTube Trend Analyzer
    `.trim();

    navigator.clipboard.writeText(report).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="mb-8">
      {/* Header Row with Keyword & Action Button */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mb-6">
        <div>
          <h2 className="text-2xl font-bold text-gray-900 flex items-center">
            <span className="text-indigo-600 mr-2">#{searchParams?.keyword || '키워드'}</span>
            분석 결과
          </h2>
          <p className="text-gray-500 text-sm mt-1">
            기간: {searchParams?.dateRange} • 타겟: {searchParams?.language}
          </p>
        </div>
        
        <button 
          onClick={handleCopyReport}
          className={`
            flex items-center justify-center px-4 py-2.5 rounded-lg font-bold shadow-sm transition-all transform active:scale-95
            ${copied 
              ? 'bg-green-100 text-green-700 border border-green-200' 
              : 'bg-white hover:bg-gray-50 text-gray-700 border border-gray-200 hover:border-gray-300'
            }
          `}
        >
          {copied ? (
            <>
              <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
              복사 완료!
            </>
          ) : (
            <>
              <svg className="w-5 h-5 mr-2 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3"></path></svg>
              분석 리포트 공유
            </>
          )}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Metrics Row */}
        <div className="lg:col-span-3 grid grid-cols-1 md:grid-cols-3 gap-4">
          {/* Growth Score */}
          <div className="bg-white rounded-xl shadow-sm p-6 flex flex-col items-center justify-center border border-gray-100">
            <span className="text-gray-400 text-sm font-medium mb-1 uppercase tracking-wider">성장 잠재력</span>
            <div className="flex items-baseline">
              <span className={`text-4xl font-extrabold ${getScoreColor(data.growthScore)}`}>
                {data.growthScore}
              </span>
              <span className="text-gray-400 text-sm ml-1">/ 100</span>
            </div>
          </div>

          {/* Competition */}
          <div className="bg-white rounded-xl shadow-sm p-6 flex flex-col items-center justify-center border border-gray-100">
            <span className="text-gray-400 text-sm font-medium mb-1 uppercase tracking-wider">경쟁 강도</span>
            <span className={`px-4 py-1 rounded-full text-lg font-bold ${getCompColor(data.competitionLevel)}`}>
              {getCompLabel(data.competitionLevel)}
            </span>
          </div>

          {/* Keywords Count */}
          <div className="bg-white rounded-xl shadow-sm p-6 flex flex-col items-center justify-center border border-gray-100">
            <span className="text-gray-400 text-sm font-medium mb-1 uppercase tracking-wider">핵심 토픽</span>
            <span className="text-4xl font-extrabold text-violet-600">
              {data.trendTopics.length}
            </span>
            <span className="text-gray-400 text-xs">개 발견됨</span>
          </div>
        </div>

        {/* Summary Box */}
        <div className="lg:col-span-2 bg-white rounded-xl shadow-sm p-6 border border-gray-100 flex flex-col justify-between">
          <div>
            <h3 className="text-lg font-bold text-gray-800 mb-3 flex items-center">
              <svg className="w-5 h-5 mr-2 text-indigo-500" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
              AI 트렌드 요약
            </h3>
            <p className="text-gray-600 leading-relaxed text-sm lg:text-base">
              {data.summary}
            </p>
          </div>
          
          {data.sources && data.sources.length > 0 && (
            <div className="mt-4 pt-4 border-t border-gray-100">
              <p className="text-xs text-gray-400 font-semibold mb-2">출처 (Sources):</p>
              <div className="flex flex-wrap gap-2">
                {data.sources.map((src, i) => (
                  <a key={i} href={src.uri} target="_blank" rel="noopener noreferrer" className="text-xs text-blue-500 hover:underline truncate max-w-[200px]">
                    {src.title || src.uri}
                  </a>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Chart */}
        <div className="lg:col-span-1 bg-white rounded-xl shadow-sm p-6 border border-gray-100">
          <h3 className="text-lg font-bold text-gray-800 mb-4">토픽 관심도</h3>
          <div className="h-48 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart layout="vertical" data={data.trendTopics} margin={{ top: 5, right: 30, left: 20, bottom: 5 }}>
                <XAxis type="number" hide />
                <YAxis dataKey="topic" type="category" width={80} tick={{fontSize: 12}} />
                <Tooltip cursor={{fill: '#f3f4f6'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1)'}} />
                <Bar dataKey="score" radius={[0, 4, 4, 0]} barSize={20}>
                  {data.trendTopics.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={barColors[index % barColors.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DashboardHeader;